# Generated by Django 3.2 on 2021-04-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20210417_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('sport', models.CharField(max_length=300)),
                ('time', models.DateTimeField(auto_now=True)),
                ('team1', models.CharField(max_length=300)),
                ('team2', models.CharField(max_length=300)),
                ('winner', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
