# Generated by Django 3.2 on 2021-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_bets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bets',
            name='win',
        ),
        migrations.AddField(
            model_name='bets',
            name='result',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='team1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='team2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='team_bet',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='winloss',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bets',
            name='game_ID',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
