# Generated by Django 3.2 on 2021-04-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_auto_20210425_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_ID', models.PositiveIntegerField()),
                ('team1_odds', models.DecimalField(decimal_places=2, max_digits=3)),
                ('team2_odds', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
