# Generated by Django 3.2 on 2021-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_dotaplayerranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='dotaplayerranking',
            name='steamid',
            field=models.TextField(null=True),
        ),
    ]
