# Generated by Django 3.2 on 2021-04-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_dotaplayerranking_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dotaplayerranking',
            name='rank',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
