# Generated by Django 3.2 on 2021-04-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_rename_time_games_time_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='time_data',
            field=models.DateTimeField(),
        ),
    ]
