# Generated by Django 3.2 on 2021-05-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_alter_games_time_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='date_placed',
            field=models.DateTimeField(),
        ),
    ]
