# Generated by Django 3.2 on 2021-05-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_bets_date_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
