# Generated by Django 3.2 on 2021-05-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0016_bets_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='team1_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='team1_odds',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='games',
            name='team2_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='games',
            name='team2_odds',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=3),
        ),
    ]
