# Generated by Django 3.2 on 2021-05-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_auto_20210502_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bets',
            name='bet_odds',
            field=models.FloatField(default=1.5),
        ),
    ]
