# Generated by Django 3.2 on 2021-05-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0021_alter_bets_bet_odds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='team1_odds',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='games',
            name='team2_odds',
            field=models.FloatField(default=1.5),
        ),
    ]
